# Overrides for the public Magnolia web application.
magnolia.bootstrap.authorInstance=false
magnolia.bootstrap.dir=WEB-INF/bootstrap/public WEB-INF/bootstrap/common
magnolia.update.auto=true
magnolia.develop=false
magnolia.bootstrap.samples=false

# A public instance does not need an interactive administrator account. This also
# prevents the initial password form from blocking incoming publishing requests.
magnolia.superuser.bootstrap.enabled=false
