# Public Magnolia instance inside the production Docker network.
magnolia.publishing.receivers[0].name=magnoliaPublic
magnolia.publishing.receivers[0].url=http://magnolia-public:8080
magnolia.publishing.receivers[0].enabled=true
