import { INTAKE_FIELDS, POLICY_VERSION, PRODUCT } from './sparring.mjs';
export const dataRules = `<details><summary>Hinweise zum Umgang mit Daten</summary><p><strong>Grün:</strong> Rollen, Beobachtungen, Zusammenhänge und gewünschte Wirkung beschreiben.</p><p><strong>Gelb:</strong> Unternehmens-, Projekt- und Produktnamen sowie Budgets abstrahieren.</p><p><strong>Rot:</strong> Keine personenbezogenen Daten Dritter, Gesundheitsdaten oder sonstigen sensiblen Angaben, Zugangsdaten, Geschäftsgeheimnisse oder internen Dokumente eingeben. Keine Uploads.</p><p>Deine Angaben werden für das persönliche Sparring gespeichert. Inhalte werden nicht an KI übergeben und nicht für den Offlinezugriff gespeichert. Geplante Löschung: 30 Tage nach Abschluss. Die Bestätigung dieser Regeln ist keine Datenschutz-Einwilligung. Einzelheiten stehen in der <a href="https://cleonhardt.de/datenschutz">Datenschutzerklärung</a>.</p></details>`;
const labels = { intake: 'Intake ausfüllen', ready: 'Bereit zum Start', active: 'Aktiv', completed: 'Abgeschlossen', cancelled: 'Storniert' };
export function sparringList(items, clients, { escapeHtml: h, nonce }) {
  return `<nav><a href="/workspace/">Zum Workspace</a></nav><h1>Meine Sparrings</h1><p>${PRODUCT.name} · 5 Arbeitstage · 249 € netto · ausschließlich B2B</p><p>Persönliche Einzelfallberatung zu einem vorab vereinbarten Thema. Kein Kurs oder Lehrgang, keine vorgegebenen Lerninhalte und keine Lernerfolgskontrolle. Keine automatische Verlängerung. Start und Reaktionsrahmen werden persönlich abgestimmt.</p><p>Der Workspace löst keine Bestellung aus. Ein Vertrag entsteht ausschließlich durch ein zuvor übermitteltes individuelles Angebot und dessen Annahme in Textform.</p>${items.length ? items.map(e => `<section class="content-card"><h2>${h(e.product.name)}</h2><p>${labels[e.status]}</p><a class="button" href="/workspace/sparring/${e.id}">Sparring öffnen</a></section>`).join('') : '<p>Noch kein Sparring zugeordnet.</p>'}${clients ? `<section class="account-card"><h2>Sparring zuordnen</h2><p>Erst nach manueller Prüfung des B2B-Auftrags und dokumentierter Annahme des individuellen Angebots anlegen. Hier wird keine Bestellung ausgelöst.</p><form method="post" action="/workspace/sparring"><input type="hidden" name="nonce" value="${nonce}"><label>Kundenkonto<select name="clientId" required>${clients.map(c => `<option value="${h(c.id)}">${h(c.name)}</option>`).join('')}</select></label><button>Zuordnen</button></form></section>` : ''}`;
}
export function sparringDetail(e, user, { escapeHtml: h, nonce, requestId }) {
  const coach = user.role === 'owner';
  const form = (action, fields, label) => `<form method="post" action="/workspace/sparring/${e.id}" autocomplete="off"><input type="hidden" name="nonce" value="${nonce}"><input type="hidden" name="action" value="${action}">${fields}<button>${label}</button></form>`;
  const intake = e.status === 'intake' && !coach ? form('intake', Object.entries(INTAKE_FIELDS).map(([key, label]) => `<label>${label}<textarea name="${key}" required maxlength="2000" rows="3" spellcheck="false"></textarea></label>`).join('') + `<label><input type="checkbox" name="business" value="yes" required> Ich nutze das Sparring ausschließlich für Zwecke meiner gewerblichen oder selbständigen beruflichen Tätigkeit. Die Beauftragung wurde vorab individuell in Textform vereinbart.</label><label><input type="checkbox" name="accepted" value="${POLICY_VERSION}" required> Ich habe die Datenregeln gelesen und berücksichtige sie.</label>`, 'Intake abschließen') : '';
  const summary = e.intake ? `<details><summary>Mein Anliegen</summary>${Object.entries(INTAKE_FIELDS).map(([key, label]) => `<h3>${label}</h3><p class="sparring-text">${h(e.intake[key])}</p>`).join('')}</details>` : '';
  return `<nav><a href="/workspace/sparring">Alle Sparrings</a></nav><h1>${h(e.product.name)}</h1><p>${labels[e.status]}${e.endsAt ? ` · Ende: ${new Intl.DateTimeFormat('de-DE', { timeZone: 'Europe/Berlin', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(e.endsAt))}` : ''}</p><p>Ein vorab vereinbartes Thema · fünf Arbeitstage (Mo–Fr, Feiertage eingeschlossen) · persönliche Einzelfallberatung · asynchron.</p>${dataRules}${intake}${summary}${coach && e.status === 'ready' ? form('start', '', 'Vereinbarten Start bestätigen') : ''}${coach && e.status === 'active' ? form('complete', '', 'Sparring abschließen') : ''}${coach && !['completed', 'cancelled'].includes(e.status) ? form('cancel', '', 'Sparring stornieren') : ''}<section data-sparring="${e.id}" data-user="${h(user.id)}" aria-label="Nachrichten"><div id="sparring-messages">${e.messages.map(m => `<article><h3>${m.senderId === user.id ? 'Du' : coach ? 'Kunde' : 'Christian'}</h3><time>${h(m.createdAt)}</time><p class="sparring-text">${h(m.body)}</p></article>`).join('')}</div><p id="sparring-update" role="status"></p></section>${e.status === 'active' ? form('message', `<input type="hidden" name="requestId" value="${requestId}"><label>Nachricht<textarea name="body" maxlength="10000" rows="5" required spellcheck="false"></textarea></label>`, 'Senden') : ''}${e.messages.length ? form('read', `<input type="hidden" name="messageId" value="${e.messages.at(-1).id}">`, 'Bis hier als gelesen markieren') : ''}<script type="module" src="/workspace/assets/sparring.mjs"></script>`;
}
