import info.magnolia.context.MgnlContext
import javax.jcr.Node

def website = MgnlContext.getJCRSession('website')
println 'Insight-Vertiefung gestartet.'

Map<String, String> depth = [
  'warum-produktorganisationen-nicht-an-fehlenden-methoden-scheitern': '''
<h3>Ein typisches Muster</h3><p>Eine Organisation führt ein neues Priorisierungsverfahren ein. Die Kriterien sind nachvollziehbar, die Workshops gut moderiert und dennoch werden wenige Wochen später dieselben Entscheidungen erneut geöffnet. Das Verfahren ist nicht zwingend falsch. Es arbeitet nur an der sichtbaren Oberfläche, während Bereiche weiterhin unterschiedliche Ziele verfolgen und niemand das Mandat besitzt, eine Entscheidung verbindlich zu schließen.</p>
<h3>Die ChOS-Sicht</h3><p>Unter <strong>Richtung</strong> zeigt sich, ob ein gemeinsames Ergebnis existiert. <strong>Entscheidungen</strong> klären, wer eine Priorität schließen darf. <strong>Verantwortung</strong> fragt, wer ihre Folgen trägt. <strong>Zusammenarbeit</strong> macht sichtbar, welche Interessen zusammengebracht werden müssen. Unter <strong>Lernen</strong> wird geprüft, ob die Priorisierung tatsächlich bessere Ergebnisse erzeugt. Erst dieses Zusammenspiel zeigt, ob eine Methode unterstützt oder lediglich bestehende Widersprüche ordentlicher dokumentiert.</p>
<h3>Woran Sie ein Systemproblem erkennen</h3><ul class="mvp-checks"><li>Die Methode wird korrekt angewendet, aber Entscheidungen bleiben unverbindlich.</li><li>Ausnahmen werden regelmäßig außerhalb des vereinbarten Prozesses beschlossen.</li><li>Teams sollen Ergebnisse verantworten, dürfen relevante Zielkonflikte aber nicht entscheiden.</li><li>Jeder Bereich kann seine eigene Priorität sachlich gut begründen.</li></ul>
<h3>Ein kleiner Test</h3><p>Nehmen Sie eine einzige strittige Prioritätsentscheidung. Benennen Sie ein gemeinsames Erfolgskriterium, die entscheidende Rolle, notwendige Beiträge und die Bedingungen, unter denen die Entscheidung wieder geöffnet werden darf. Beobachten Sie vier Wochen lang nicht die Einhaltung der Methode, sondern die tatsächlichen Eingriffe und Ausnahmen.</p>
<h3>Wann eine neue Methode dennoch hilft</h3><p>Wenn Richtung, Mandat und Verantwortung grundsätzlich geklärt sind, kann ein Framework Sprache vereinheitlichen und Entscheidungen beschleunigen. Die Diagnose richtet sich also nicht gegen Methoden. Sie verhindert nur, dass eine bekannte Lösung für einen ungeklärten Mechanismus eingesetzt wird.</p>''',

  'diagnose-vor-eingriff': '''
<h3>Warum vorschnelle Lösungen so überzeugend wirken</h3><p>Unter Zeitdruck wird eine plausible Erklärung leicht mit einer bewiesenen Ursache verwechselt. Wenn Entscheidungen langsam sind, klingt ein kleineres Gremium vernünftig. Wenn Teams wenig Initiative zeigen, klingt mehr Verantwortung vernünftig. Beide Eingriffe können helfen – oder das Problem verschärfen, wenn fehlende Informationen, reale Risiken oder widersprüchliche Ziele der eigentliche Grund sind.</p>
<h3>Eine einfache Evidenzleiter</h3><ol><li><strong>Vorfall:</strong> Was ist konkret geschehen?</li><li><strong>Muster:</strong> In welchen weiteren Situationen tritt es auf?</li><li><strong>Hypothese:</strong> Welcher Mechanismus könnte das Muster erklären?</li><li><strong>Gegenbeleg:</strong> Wo müsste das Muster auftreten, tut es aber nicht?</li><li><strong>Test:</strong> Welche kleine Veränderung unterscheidet zwei Erklärungen?</li></ol>
<h3>Beispiel: eine wiederholt geöffnete Entscheidung</h3><p>Die erste Erklärung lautet häufig: Stakeholder akzeptieren den Prozess nicht. Eine zweite lautet: Die Entscheidung verwendet Kriterien, die für Vertrieb und Produkt unterschiedliche Folgen haben. Eine dritte: Niemand besitzt das sichtbare Mandat, einen Konflikt zu schließen. Ein weiterer Workshop prüft keine dieser Erklärungen. Ein befristetes Entscheidungsmandat oder ein gemeinsames Erfolgskriterium dagegen schon.</p>
<h3>Die fünf Perspektiven als Gegenprüfung</h3><p>ChOS verhindert den Tunnelblick: Ist das gewünschte Ergebnis klar? Liegt die Entscheidung am richtigen Ort? Passen Verantwortung und Mandat zusammen? Unterstützen Beziehungen und Routinen die Vereinbarung? Gibt es eine Rückmeldung, an der Wirkung erkennbar wird?</p>
<h3>Grenze der Diagnose</h3><p>Nicht jede Entscheidung benötigt eine umfangreiche Untersuchung. Bei reversiblen, risikoarmen Fragen ist schnelles Handeln oft die beste Erkenntnisquelle. Je größer Wirkung, Reichweite und Irreversibilität eines Eingriffs sind, desto wichtiger wird jedoch eine belastbare Diagnose.</p>''',

  'unklare-rollen-sind-selten-das-eigentliche-problem': '''
<h3>Warum Rollendokumente im Alltag verblassen</h3><p>Eine Rolle kann formal eindeutig und praktisch wirkungslos sein. Ein Product Manager soll beispielsweise die Produktstrategie verantworten, während Budget, Personal, technische Risiken und Vertriebszusagen an anderen Orten entschieden werden. Das Problem ist dann nicht mangelndes Rollenverständnis, sondern eine Verantwortung ohne ausreichende Mittel.</p>
<h3>Vier Tests für eine belastbare Rolle</h3><ol><li><strong>Ergebnis:</strong> Ist klar, welches Ergebnis die Rolle besitzt?</li><li><strong>Mandat:</strong> Darf sie die dafür notwendigen Entscheidungen treffen?</li><li><strong>Information:</strong> Erreichen sie Kundenwissen, Wirtschaftsdaten und Risiken rechtzeitig?</li><li><strong>Konsequenz:</strong> Kann sie aus Ergebnissen lernen und die nächste Entscheidung verändern?</li></ol>
<h3>Der kritische Moment ist der Konflikt</h3><p>Rollen wirken nicht in ruhigen Situationen, sondern wenn Ziele kollidieren. Wer entscheidet bei einem Konflikt zwischen Liefertermin, technischem Risiko und Kundennutzen? Wer darf Nein sagen? Wann darf Führung eingreifen? Wenn diese Fragen offenbleiben, wird jede Rollenbeschreibung im Ernstfall von informeller Macht ersetzt.</p>
<h3>Ein sinnvoller Einstieg</h3><p>Wählen Sie drei wiederkehrende Entscheidungen und zeichnen Sie ihren tatsächlichen Weg nach. Vergleichen Sie formales Mandat und beobachtetes Verhalten. Vereinbaren Sie anschließend nur für diese Entscheidungen Ergebnis, Entscheidungsrecht, benötigte Beiträge und Eskalationsbedingung. Das ist überprüfbarer als eine vollständige neue Rollenmatrix.</p>
<h3>Wann Dokumentation wichtig wird</h3><p>Dokumentation ist wertvoll, sobald die Vereinbarung praktisch erprobt wurde. Dann hält sie ein funktionierendes Muster fest. Wird sie zu früh erstellt, konserviert sie oft nur Annahmen darüber, wie die Organisation funktionieren sollte.</p>''',

  'rollen-und-verantwortlichkeiten-in-produktorganisationen-klaeren': '''
<h3>Verantwortung ist mehr als Zuständigkeit</h3><p>Zuständigkeit beantwortet, wer eine Aufgabe bearbeitet. Verantwortung beantwortet, wer ein Ergebnis besitzt, Entscheidungen treffen kann und aus den Folgen lernt. Viele Produktorganisationen verteilen Aufgaben sehr genau, lassen aber offen, wer bei konkurrierenden Zielen eine verbindliche Wahl trifft.</p>
<h3>Beispiel: Produkt gegen Plattform</h3><p>Ein Produktteam benötigt kurzfristig eine Sonderlösung, die Plattformverantwortliche ablehnen. Beide Seiten handeln nachvollziehbar: Das Produkt schützt ein Kundenergebnis, die Plattform langfristige Stabilität. Eine RACI-Matrix löst den Zielkonflikt nicht. Nötig sind gemeinsame Kriterien, eine klar benannte Entscheidung und ein Ort, an dem die Folgen beider Optionen sichtbar werden.</p>
<h3>Entscheidungskarte statt Rollenmatrix</h3><p>Eine kleine Entscheidungskarte enthält: die konkrete Entscheidung, das gewünschte Ergebnis, die entscheidende Rolle, verpflichtend einzubeziehende Perspektiven, Grenzen des Mandats und einen Eskalationsgrund. Sie wird an echten Fällen getestet und erst danach verallgemeinert.</p>
<h3>Diagnosefragen</h3><ul class="mvp-checks"><li>Wer kann heute faktisch blockieren, obwohl die Rolle es nicht vorsieht?</li><li>Wer trägt Folgen, ohne entscheiden zu dürfen?</li><li>Welche Entscheidung wird in mehreren Kreisen getroffen?</li><li>Wo ersetzt Eskalation eine fehlende Regel?</li><li>Welche Information fehlt am Entscheidungsort?</li></ul>
<h3>Grenze</h3><p>Nicht jede Schnittstelle braucht eine feste Entscheidungsregel. Bei seltenen oder neuartigen Fragen kann ein bewusster gemeinsamer Entscheid sinnvoller sein. Klarheit bedeutet nicht maximale Formalisierung, sondern eine zur Häufigkeit und zum Risiko passende Vereinbarung.</p>''',

  'wann-braucht-eine-produktorganisation-ein-operating-model': '''
<h3>Das Operating Model ist bereits da</h3><p>Jede Organisation besitzt ein Operating Model – auch wenn es nie bewusst gestaltet wurde. Es steckt in Budgetzyklen, Gremien, Zielsystemen, Informationswegen, Teamgrenzen und Führungsroutinen. Die Frage ist deshalb nicht, ob ein Operating Model benötigt wird, sondern ob das bestehende noch zur Strategie passt.</p>
<h3>Drei typische Auslöser</h3><p><strong>Wachstum:</strong> Informelle Abstimmung funktioniert nicht mehr. <strong>Strategiewechsel:</strong> Neue Ziele treffen auf alte Finanzierung und Zuständigkeiten. <strong>Neue Technik:</strong> Arbeit wird schneller oder automatisierbar, doch Prüfungen und Entscheidungen bleiben unverändert. In allen drei Fällen entsteht Reibung, weil einzelne Elemente sich schneller verändern als das Gesamtsystem.</p>
<h3>Nicht beim Organigramm beginnen</h3><p>Starten Sie mit einem wichtigen Wertstrom und verfolgen Sie, wie ein Kundenergebnis entsteht. Wo warten Entscheidungen? Wo wechseln Ziele? Welche Einheit optimiert lokal? Erst danach werden Teamgrenzen und Rollen betrachtet. Sonst wird eine neue Struktur um alte Entscheidungswege gebaut.</p>
<h3>Fünf ChOS-Prüffragen</h3><ul class="mvp-checks"><li>Richtung: Ist das gemeinsame Ergebnis übersetzbar?</li><li>Entscheidungen: Liegen häufige Entscheidungen nahe an der nötigen Information?</li><li>Verantwortung: Passen Ergebnis, Mandat und Konsequenz zusammen?</li><li>Zusammenarbeit: Unterstützen Schnittstellen den Wertstrom?</li><li>Lernen: Verändert Rückmeldung tatsächlich Prioritäten und Strukturen?</li></ul>
<h3>Wann kein Redesign nötig ist</h3><p>Einzelne Konflikte, personelle Spannungen oder ein vorübergehender Engpass rechtfertigen noch kein neues Operating Model. Ein Redesign wird sinnvoll, wenn dieselben Muster über Teams und Situationen hinweg auftreten und durch lokale Anpassungen nicht verschwinden.</p>''',

  'annahmen-vor-einer-produktentscheidung-pruefen': '''
<h3>Die gefährlichsten Annahmen wirken wie Fakten</h3><p>„Kunden brauchen diese Funktion“, „die Plattform skaliert nicht“ oder „der Markt erwartet eine schnelle Einführung“ klingen eindeutig. Häufig vermischen solche Sätze Beobachtung, Interpretation und Schlussfolgerung. Ein Decision Review macht diese Kette sichtbar, ohne die Entscheidung durch endlose Analyse zu lähmen.</p>
<h3>Beispiel einer Entscheidungskette</h3><p>Beobachtung: Drei große Kunden fragen nach einer Funktion. Annahme: Die Funktion ist für den gesamten Zielmarkt relevant. Schlussfolgerung: Sie erhält höchste Priorität. Alternative Erklärungen könnten sein, dass nur ein Segment betroffen ist oder ein bestehender Ablauf missverstanden wird. Je nach Erklärung wäre die richtige Investition eine andere.</p>
<h3>Risiko statt Gewissheit steuern</h3><p>Nicht jede Annahme muss geprüft werden. Entscheidend sind Annahmen, deren Irrtum großen Schaden erzeugt und deren Prüfung bezahlbar ist. Dafür helfen drei Kriterien: Auswirkung, Unsicherheit und Umkehrbarkeit. Hohe Wirkung, geringe Evidenz und schwer umkehrbare Folgen verlangen die stärkste Gegenprüfung.</p>
<h3>Ein praktisches Red Team</h3><ul class="mvp-checks"><li>Formulieren Sie die bevorzugte Option und ihre Begründung in einem Satz.</li><li>Markieren Sie Beobachtungen, Annahmen und Bewertungen getrennt.</li><li>Entwickeln Sie mindestens eine plausible Gegenhypothese.</li><li>Fragen Sie, welche Information die Präferenz tatsächlich ändern würde.</li><li>Definieren Sie einen Test oder akzeptieren Sie das Risiko ausdrücklich.</li></ul>
<h3>Grenze</h3><p>Ein Review soll eine Entscheidung verbessern, nicht Verantwortung verdünnen. Nach der Gegenprüfung muss klar bleiben, wer entscheidet, bis wann und unter welchen neuen Informationen die Entscheidung erneut betrachtet wird.</p>''',

  'organisationsdiagnose-statt-standardberatung': '''
<h3>Warum Standardlösungen trotzdem attraktiv sind</h3><p>Sie geben schnell Orientierung, lassen sich budgetieren und vermitteln Handlungsfähigkeit. Das ist nicht grundsätzlich schlecht. Problematisch wird es, wenn die Lösung bereits feststeht, bevor geklärt wurde, welcher Mechanismus das beobachtete Muster erzeugt.</p>
<h3>Ein Symptom, vier mögliche Ursachen</h3><p>„Teams liefern zu langsam“ kann auf zu große Arbeitspakete, fehlende Entscheidungen, technische Abhängigkeiten oder ständig wechselnde Ziele zurückgehen. Mehr agile Rituale adressieren höchstens einen Teil davon. Eine Diagnose unterscheidet diese Erklärungen anhand konkreter Fälle und sucht bewusst nach Gegenbelegen.</p>
<h3>Was gute Diagnose nicht ist</h3><p>Sie ist keine monatelange Bestandsaufnahme und keine Sammlung aller Beschwerden. Sie beginnt mit einer begrenzten Frage, betrachtet mehrere Perspektiven und endet mit priorisierten Hypothesen. Ihre Qualität zeigt sich darin, ob daraus unterschiedliche, überprüfbare Handlungsoptionen entstehen.</p>
<h3>Ein minimales Diagnoseformat</h3><ol><li>Eine wiederkehrende Situation präzise beschreiben.</li><li>Zwei bis vier konkrete Fälle rekonstruieren.</li><li>Betroffene Entscheidungsorte und Ziele vergleichen.</li><li>Mindestens zwei Ursachenhypothesen formulieren.</li><li>Einen kleinen Test mit erwarteter Beobachtung vereinbaren.</li></ol>
<h3>Wann ein Standard sinnvoll ist</h3><p>Bei bekannten, stabilen Problemen mit klarer Ursache kann ein bewährtes Vorgehen die wirtschaftlichste Wahl sein. ChOS verlangt keine Individualisierung um ihrer selbst willen. Es verlangt nur, dass Problem und Lösung nachvollziehbar zusammenpassen.</p>''',

  'product-organisation-diagnostic-ablauf-und-ergebnis': '''
<h3>Die Untersuchungsfrage bestimmt die Qualität</h3><p>„Wie verbessern wir unsere Produktorganisation?“ führt fast zwangsläufig zu einer langen Wunschliste. Eine gute Frage verbindet ein beobachtetes Muster mit einer relevanten Wirkung: Warum werden gemeinsame Prioritäten zwischen drei Bereichen regelmäßig innerhalb weniger Wochen wieder aufgehoben?</p>
<h3>Formale und tatsächliche Organisation vergleichen</h3><p>Strategien, Rollenbilder und Prozessbeschreibungen zeigen den Anspruch. Rekonstruierte Entscheidungen zeigen den Alltag. Interviews erklären unterschiedliche Wahrnehmungen. Kennzahlen zeigen mögliche Wirkung. Kein einzelner Datentyp reicht; interessant sind die Abweichungen zwischen ihnen.</p>
<h3>Aus Aussagen werden prüfbare Hypothesen</h3><p>„Führung vertraut den Teams nicht“ ist zunächst eine Bewertung. Prüfbarer wäre: Führung greift ein, weil wirtschaftliche Risiken erst nach der Teamentscheidung sichtbar werden. Daraus folgt ein anderer Test als aus der Hypothese, dass Mandate bewusst nicht akzeptiert werden.</p>
<h3>Was ein gutes Ergebnis enthält</h3><ul class="mvp-checks"><li>eine beantwortete Untersuchungsfrage und klare Systemgrenze</li><li>beobachtete Muster statt einer Sammlung von Meinungen</li><li>priorisierte Hypothesen einschließlich Gegenbelegen</li><li>Risiken und Wechselwirkungen der möglichen Eingriffe</li><li>wenige nächste Schritte mit erwarteter Wirkung und Lernsignal</li></ul>
<h3>Was es nicht verspricht</h3><p>Eine Diagnose liefert keine mathematische Gewissheit über soziale Systeme. Sie reduziert relevante Unsicherheit und macht Annahmen transparent. Gute Führung behält deshalb nach dem Eingriff die Beobachtung bei und korrigiert das Vorgehen, wenn die erwartete Wirkung ausbleibt.</p>''',

  'wann-ist-executive-sparring-sinnvoll': '''
<h3>Die Einsamkeit komplexer Entscheidungen</h3><p>Je größer die Verantwortung, desto weniger Personen können intern vollständig unabhängig widersprechen. Mitarbeitende sind betroffen, Kolleginnen vertreten eigene Bereiche und Vorgesetzte erwarten eine Empfehlung. Sparring schafft einen vertraulichen Raum, in dem eine reale Entscheidung ohne politische Nebenagenda geprüft werden kann.</p>
<h3>Worum es im Sparring tatsächlich geht</h3><p>Nicht jede Session braucht ein persönliches Entwicklungsthema. Häufig geht es um eine konkrete Entscheidung: eine Reorganisation, einen Konflikt zwischen Führungskräften, eine Priorität oder die Frage, ob überhaupt eingegriffen werden sollte. Das Gegenüber hilft, Beobachtung und Deutung zu trennen, blinde Flecken sichtbar zu machen und Konsequenzen verschiedener Optionen durchzuspielen.</p>
<h3>Ein sinnvoller Rhythmus</h3><p>Vor einer Entscheidung werden Ziel, Annahmen und Risiken geklärt. Danach wird beobachtet, was tatsächlich geschieht. In der nächsten Schleife werden nicht nur Ergebnisse, sondern auch die eigene Entscheidungslogik ausgewertet. So entsteht Lernen über mehrere Situationen hinweg.</p>
<h3>Woran gutes Sparring erkennbar ist</h3><ul class="mvp-checks"><li>Entscheidungen werden klarer, nicht an das Gegenüber delegiert.</li><li>Widerspruch ist konkret und begründet.</li><li>Wiederkehrende Muster werden früher erkannt.</li><li>Optionen enthalten Konsequenzen und Beobachtungskriterien.</li><li>Die Zusammenarbeit erzeugt keine dauerhafte Abhängigkeit.</li></ul>
<h3>Wann etwas anderes nötig ist</h3><p>Fehlt Fachwissen für eine klar begrenzte Aufgabe, ist Beratung passender. Geht es primär um psychische Gesundheit, ist therapeutische Unterstützung richtig. Muss ein Team gemeinsam entscheiden, ersetzt individuelles Sparring keinen moderierten Organisationsprozess.</p>''',

  'warum-ai-einfuehrung-ein-operating-model-thema-ist': '''
<h3>Vom Werkzeug zur veränderten Arbeit</h3><p>Ein einzelner Assistent kann Texte schneller zusammenfassen, ohne die Organisation zu verändern. Sobald Ergebnisse jedoch in Entscheidungen einfließen, Aufgaben automatisch weitergegeben werden oder ein System selbst handelt, verändern sich Informationswege, Kontrollpunkte und Verantwortung. Dann reicht eine technische Einführung nicht mehr.</p>
<h3>Ein typisches Beispiel</h3><p>Ein System bewertet Kundenanfragen und schlägt Prioritäten vor. Die Bearbeitung wird schneller, doch niemand weiß, wer falsche Einstufungen überwacht oder wann ein Mensch abweichen darf. Teams folgen der Empfehlung, weil sie objektiv wirkt. Führung erwartet trotzdem menschliche Verantwortung. So entsteht eine Lücke zwischen faktischer Entscheidung und formaler Verantwortung.</p>
<h3>AI innerhalb der fünf ChOS-Perspektiven</h3><ul class="mvp-checks"><li><strong>Richtung:</strong> Welches Ergebnis soll sich verbessern – und für wen?</li><li><strong>Entscheidungen:</strong> Was wird vorgeschlagen, vorbereitet oder selbstständig ausgeführt?</li><li><strong>Verantwortung:</strong> Wer besitzt Ergebnis, Kontrolle und Konsequenzen?</li><li><strong>Zusammenarbeit:</strong> Wie funktionieren Übergaben und Widerspruch?</li><li><strong>Lernen:</strong> Welche Fehler und Nebenwirkungen werden sichtbar?</li></ul>
<h3>Ein begrenzter Einstieg</h3><p>Wählen Sie einen realen Ablauf. Markieren Sie, wo Information entsteht, wo eine Entscheidung fällt und wo Verantwortung liegt. Ergänzen Sie erst danach die technische Unterstützung. Vereinbaren Sie Grenzen, Eskalationen und Messgrößen vor dem Piloten, nicht erst nach einem Vorfall.</p>
<h3>Grenze</h3><p>Nicht jede Nutzung benötigt ein neues Operating Model. Bei persönlicher, reversibler Unterstützung mit menschlicher Prüfung reichen oft klare Arbeitsregeln. Der organisatorische Gestaltungsbedarf steigt mit Autonomie, Reichweite, Geschwindigkeit und möglichem Schaden.</p>''',

  'decision-rights-zwischen-mensch-und-ai': '''
<h3>Die falsche Frage lautet: Mensch oder AI?</h3><p>In der Praxis besteht eine Entscheidung aus mehreren Schritten: Informationen sammeln, Optionen erzeugen, bewerten, auswählen, ausführen und Wirkung beobachten. Diese Schritte können unterschiedlich verteilt werden. Dadurch lässt sich Autonomie gezielt gestalten, statt sie pauschal zu erlauben oder zu verbieten.</p>
<h3>Fünf Stufen der Beteiligung</h3><ol><li>Information verdichten</li><li>Optionen vorschlagen</li><li>eine Empfehlung mit Begründung liefern</li><li>innerhalb klarer Grenzen ausführen</li><li>selbstständig handeln und bei Ausnahmen eskalieren</li></ol><p>Je höher die Stufe, desto klarer müssen Ziel, Datenqualität, Grenzen, Überwachung und Rücknahme sein.</p>
<h3>Beispiel: Preisentscheidung</h3><p>Ein System kann Nachfrage analysieren und einen Preis empfehlen. Die mögliche Wirkung ist unmittelbar, aber meist reversibel. Anders ist eine automatische Vertragsablehnung: Sie betrifft Rechte und Kundenbeziehungen und kann schwer nachvollziehbare Folgen haben. Dasselbe Modell kann deshalb in einem Fall ausführen und im anderen nur vorbereiten.</p>
<h3>Verantwortung bleibt konkret</h3><p>„Der Algorithmus hat entschieden“ ist keine Verantwortungsregel. Eine Rolle oder Einheit muss die Einsatzgrenzen besitzen, Ergebnisse überwachen und bei Fehlern handeln können. Dafür benötigt sie Information und echtes Mandat – nicht nur eine formale Zuständigkeit.</p>
<h3>Prüffragen</h3><ul class="mvp-checks"><li>Wie groß und wie reversibel ist die Wirkung?</li><li>Welche Unsicherheit enthält die Empfehlung?</li><li>Wie schnell wird ein Fehler erkannt?</li><li>Kann ein Mensch sinnvoll eingreifen oder bestätigt er nur noch?</li><li>Wer darf den Ablauf stoppen?</li></ul>''',

  'schlechte-prozesse-nicht-nur-schneller-machen': '''
<h3>Ein schneller Schritt kann den Gesamtprozess verschlechtern</h3><p>Wenn Analysen in Minuten statt Tagen entstehen, wächst häufig die Menge der Ergebnisse. Muss danach jedes Ergebnis geprüft, abgestimmt und freigegeben werden, wird der nächste Engpass größer. Lokale Effizienz erzeugt mehr Arbeit im restlichen System.</p>
<h3>Beispiel aus der Produktarbeit</h3><p>Automatisierte Auswertung erzeugt täglich neue Kundenhypothesen. Product Manager prüfen mehr Vorschläge, Design und Entwicklung erhalten häufiger wechselnde Anforderungen und die Zahl paralleler Initiativen steigt. Die Analyse ist schneller, das Produktergebnis jedoch nicht. Es fehlt eine Entscheidung darüber, welche Information relevant ist und wann daraus Arbeit entstehen darf.</p>
<h3>Den Ablauf vom Ergebnis rückwärts lesen</h3><p>Beginnen Sie nicht beim automatisierbaren Arbeitsschritt, sondern beim gewünschten Ergebnis. Welche Entscheidung muss dafür besser werden? Welche Information benötigt sie? Wo entstehen Wartezeit, Nacharbeit und Übergaben? Erst dann wird sichtbar, ob Technik einen Engpass löst oder nur verschiebt.</p>
<h3>Ein sinnvoller Pilot</h3><ol><li>Einen klar begrenzten End-to-end-Ablauf wählen.</li><li>Durchlaufzeit, Qualität und Nacharbeit vorab erfassen.</li><li>Entscheidungen und Verantwortliche sichtbar machen.</li><li>Nur einen relevanten Teil verändern.</li><li>Gesamtwirkung statt erzeugter Menge messen.</li></ol>
<h3>Wann Automatisierung ohne Redesign reicht</h3><p>Bei stabilen, regelbasierten Aufgaben mit klaren Ein- und Ausgaben kann eine lokale Verbesserung völlig ausreichen. Ein Redesign wird nötig, wenn Ergebnisse neue Entscheidungen auslösen, mehrere Rollen betreffen oder sich Fehler schnell durch den gesamten Ablauf vervielfältigen.</p>'''
]

depth.each { String slug, String html ->
    String path = '/insights/' + slug
    println "Bearbeite ${path} ..."
    if (!website.nodeExists(path + '/main')) throw new IllegalStateException("Insight fehlt: ${path}")
    Node area = website.getNode(path + '/main')
    if (area.hasNode('insight-depth')) area.getNode('insight-depth').remove()
    Node component = area.addNode('insight-depth', 'mgnl:component')
    component.setProperty('mgnl:template', 'meine-website:components/text')
    component.setProperty('heading', 'Vertiefung und Anwendung')
    component.setProperty('text', html)
    component.setProperty('showBackground', false)

    String before = null
    for (Node child : area.nodes) {
        if (!child.hasProperty('mgnl:template')) continue
        String template = child.getProperty('mgnl:template').string
        if (template == 'meine-website:components/callToAction' || template == 'meine-website:components/faq' || template == 'meine-website:components/relatedInsights') {
            before = child.getName()
            break
        }
    }
    if (before != null) area.orderBefore(component.getName(), before)
    website.save()
    println "${path}: vertieft"
}

println "${depth.size()} Insights inhaltlich vertieft."
